# Generated by Django 2.1 on 2019-07-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20180807_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(db_index=True, max_length=200)),
                ('state_name', models.CharField(db_index=True, max_length=200)),
                ('last_voted_on', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'State',
            },
        ),
    ]
