# Generated by Django 2.1 on 2019-07-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(db_index=True, max_length=200)),
                ('grade', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'Subject',
            },
        ),
        migrations.RenameField(
            model_name='state',
            old_name='last_voted_on',
            new_name='last_modified_on',
        ),
    ]
