# Generated by Django 2.1 on 2019-07-31 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20190731_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(db_index=True, max_length=200)),
                ('district_head_name', models.CharField(db_index=True, max_length=200)),
                ('district_contact_name', models.IntegerField(blank=True, db_index=True, max_length=20)),
                ('district_email_name', models.EmailField(blank=True, max_length=70)),
                ('mswo_head_name', models.CharField(db_index=True, max_length=200)),
                ('mswo_contact_name', models.IntegerField(blank=True, db_index=True, max_length=20)),
                ('mswo_email_name', models.EmailField(blank=True, max_length=70)),
                ('last_modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.State')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'District',
            },
        ),
    ]
